- hosts: all
  become: 'yes'
  tasks:
    - name: 'Get UUID'
      become: 'no'
      local_action: shell uuidgen | cut -d- -f1
      register: uuid
    - name: 'Set hostname'
      hostname:
        name: wx-map-{{uuid.stdout}}
    - name: 'Fetch Docker'
      get_url:
        url: https://get.docker.com
        dest: /tmp/docker.sh
        mode: 0777
    - name: 'Install Docker'
      shell: /tmp/docker.sh
    - name: 'Install docker-compose prereqs'
      apt:
        pkg:
        - libffi-dev
        - libssl-dev
        - python3
        - python3-pip
    - name: 'Install docker-compose'
      shell: pip3 install docker-compose
      #      shell: |
      #        apt-get install -y libffi-dev libssl-dev python3 python3-pip
      #        apt-get remove python-confiarser
      #        pip3 install docker-compose
    - name: 'Add pi to docker group'
      user:
        name: 'pi'
        groups: 'docker'
        append: yes
    - name: 'Install git'
      apt:
        name: 'git'
        state: 'present'
        update_cache: 'yes'
    - name: 'Fetch wx-maps-os'
      git:
        repo: 'https://github.com/wx-maps/wx-maps-os.git'
        dest: '/etc/wx-maps'
    - name: 'Add wx-maps profile'
      blockinfile:
        path: /etc/profile
        block: |
          if [[ -f /etc/wx-maps/profile ]]; then 
            . /etc/wx-maps/profile
          fi
    - name: 'Start WX Maps Containers'
      shell: . /etc/wx-maps/profile && wx-maps up



